!function(){function v(a){return this.m?b(a).f():a}function w(a,c,d,e){if(a===c)return 0!==a||1/a==1/c;if(null==a||null==c)return a===c;a instanceof b&&(a=a.c);c instanceof b&&(c=c.c);var h=n.call(a);if(h!=n.call(c))return!1;switch(h){case "[object String]":return a==String(c);case "[object Number]":return a!=+a?c!=+c:0==a?1/a==1/c:a==+c;case "[object Date]":case "[object Boolean]":return+a==+c;case "[object RegExp]":return a.source==c.source&&a.global==c.global&&a.multiline==c.multiline&&a.ignoreCase==
c.ignoreCase}if("object"!=typeof a||"object"!=typeof c)return!1;for(var f=d.length;f--;)if(d[f]==a)return e[f]==c;var f=a.constructor,g=c.constructor;if(f!==g&&!(b.a(f)&&f instanceof f&&b.a(g)&&g instanceof g))return!1;d.push(a);e.push(c);f=0;g=!0;if("[object Array]"==h){if(f=a.length,g=f==c.length)for(;f--&&(g=w(a[f],c[f],d,e)););}else{for(var p in a)if(b.has(a,p)&&(f++,!(g=b.has(c,p)&&w(a[p],c[p],d,e))))break;if(g){for(p in c)if(b.has(c,p)&&!f--)break;g=!f}}return d.pop(),e.pop(),g}function x(){}
function D(a,c,d){return c&&b.every(a,b.isArray)?r.apply(d,a):(l(a,function(a){b.isArray(a)||b.j(a)?c?y.apply(d,a):D(a,c,d):d.push(a)}),d)}function E(a,c,d,e){var h={},f=z(null==c?b.b:c);return l(a,function(c,b){var k=f.call(d,c,b,a);e(h,k,c)}),h}function z(a){return b.a(a)?a:function(c){return c[a]}}function b(a){return a instanceof b?a:this instanceof b?(this.c=a,void 0):new b(a)}var A=this,O=A.e,s={},m=Array.prototype,t=Object.prototype,y=m.push,k=m.slice,r=m.concat,n=t.toString,P=t.hasOwnProperty,
F=m.forEach,G=m.map,H=m.reduce,I=m.reduceRight,J=m.filter,K=m.every,L=m.some,u=m.indexOf,M=m.lastIndexOf,t=Array.isArray,Q=Object.keys,B=Function.prototype.bind;"undefined"!=typeof exports?("undefined"!=typeof module&&module.r&&(exports=module.r=b),exports.e=b):A.e=b;b.VERSION="1.5.1";var l=b.q=b.forEach=function(a,c,d){if(null!=a)if(F&&a.forEach===F)a.forEach(c,d);else if(a.length===+a.length)for(var e=0,h=a.length;h>e&&c.call(d,a[e],e,a)!==s;e++);else for(e in a)if(b.has(a,e)&&c.call(d,a[e],e,a)===
s)break};b.map=b.K=function(a,c,b){var e=[];return null==a?e:G&&a.map===G?a.map(c,b):(l(a,function(a,f,g){e.push(c.call(b,a,f,g))}),e)};b.reduce=b.R=b.W=function(a,c,d,e){var h=2<arguments.length;if(null==a&&(a=[]),H&&a.reduce===H)return e&&(c=b.bind(c,e)),h?a.reduce(c,d):a.reduce(c);if(l(a,function(a,b,p){h?d=c.call(e,d,a,b,p):(d=a,h=!0)}),!h)throw new TypeError("Reduce of empty array with no initial value");return d};b.reduceRight=b.S=function(a,c,d,e){var h=2<arguments.length;if(null==a&&(a=[]),
I&&a.reduceRight===I)return e&&(c=b.bind(c,e)),h?a.reduceRight(c,d):a.reduceRight(c);var f=a.length;if(f!==+f)var g=b.keys(a),f=g.length;if(l(a,function(b,k,l){k=g?g[--f]:--f;h?d=c.call(e,d,a[k],k,l):(d=a[k],h=!0)}),!h)throw new TypeError("Reduce of empty array with no initial value");return d};b.find=b.O=function(a,c,b){var e;return N(a,function(a,f,g){return c.call(b,a,f,g)?(e=a,!0):void 0}),e};b.filter=b.select=function(a,c,b){var e=[];return null==a?e:J&&a.filter===J?a.filter(c,b):(l(a,function(a,
f,g){c.call(b,a,f,g)&&e.push(a)}),e)};b.reject=function(a,c,d){return b.filter(a,function(a,b,f){return!c.call(d,a,b,f)},d)};b.every=b.all=function(a,c,d){c||(c=b.b);var e=!0;return null==a?e:K&&a.every===K?a.every(c,d):(l(a,function(a,b,g){return(e=e&&c.call(d,a,b,g))?void 0:s}),!!e)};var N=b.some=b.I=function(a,c,d){c||(c=b.b);var e=!1;return null==a?e:L&&a.some===L?a.some(c,d):(l(a,function(a,b,g){return e||(e=c.call(d,a,b,g))?s:void 0}),!!e)};b.contains=b.U=function(a,c){return null==a?!1:u&&
a.indexOf===u?-1!=a.indexOf(c):N(a,function(a){return a===c})};b.Y=function(a,c){var d=k.call(arguments,2),e=b.a(c);return b.map(a,function(a){return(e?c:a[c]).apply(a,d)})};b.h=function(a,c){return b.map(a,function(a){return a[c]})};b.G=function(a,c){return b.g(c)?void 0:b.find(a,function(a){for(var b in c)if(c[b]!==a[b])return!1;return!0})};b.Q=function(a,c){return b.G(a,c)};b.max=function(a,c,d){if(!c&&b.isArray(a)&&a[0]===+a[0]&&65535>a.length)return Math.max.apply(Math,a);if(!c&&b.g(a))return-1/
0;var e={d:-1/0,value:-1/0};return l(a,function(a,b,g){b=c?c.call(d,a,b,g):a;b>e.d&&(e={value:a,d:b})}),e.value};b.min=function(a,c,d){if(!c&&b.isArray(a)&&a[0]===+a[0]&&65535>a.length)return Math.min.apply(Math,a);if(!c&&b.g(a))return 1/0;var e={d:1/0,value:1/0};return l(a,function(a,b,g){b=c?c.call(d,a,b,g):a;b<e.d&&(e={value:a,d:b})}),e.value};b.oa=function(a){var c,d=0,e=[];return l(a,function(a){c=b.random(d++);e[d-1]=e[c];e[c]=a}),e};b.pa=function(a,c,d){var e=z(c);return b.h(b.map(a,function(a,
c,b){return{value:a,index:c,i:e.call(d,a,c,b)}}).sort(function(a,c){var b=a.i,d=c.i;if(b!==d){if(b>d||void 0===b)return 1;if(d>b||void 0===d)return-1}return a.index<c.index?-1:1}),"value")};b.T=function(a,c,d){return E(a,c,d,function(a,c,d){(b.has(a,c)?a[c]:a[c]=[]).push(d)})};b.M=function(a,c,d){return E(a,c,d,function(a,c){b.has(a,c)||(a[c]=0);a[c]++})};b.C=function(a,c){var d;d=null==d?b.b:z(d);for(var e=d.call(void 0,c),h=0,f=a.length;f>h;){var g=h+f>>>1;d.call(void 0,a[g])<e?h=g+1:f=g}return h};
b.wa=function(a){return a?b.isArray(a)?k.call(a):a.length===+a.length?b.map(a,b.b):b.F(a):[]};b.size=function(a){return null==a?0:a.length===+a.length?a.length:b.keys(a).length};b.first=b.head=b.ra=function(a,c,b){return null==a?void 0:null==c||b?a[0]:k.call(a,0,c)};b.V=function(a,c,b){return k.call(a,0,a.length-(null==c||b?1:c))};b.ea=function(a,c,b){return null==a?void 0:null==c||b?a[a.length-1]:k.call(a,Math.max(a.length-c,0))};b.na=b.qa=b.P=function(a,c,b){return k.call(a,null==c||b?1:c)};b.compact=
function(a){return b.filter(a,b.b)};b.s=function(a){return D(a,!0,[])};b.Aa=function(a){return b.p(a,k.call(arguments,1))};b.k=b.unique=function(a,c,d,e){b.a(c)&&(e=d,d=c,c=!1);d=d?b.map(a,d,e):a;var h=[],f=[];return l(d,function(d,e){(c?e&&f[f.length-1]===d:b.contains(f,d))||(f.push(d),h.push(a[e]))}),h};b.ya=function(){return b.k(b.s(arguments))};b.X=function(a){var c=k.call(arguments,1);return b.filter(b.k(a),function(a){return b.every(c,function(c){return 0<=b.indexOf(c,a)})})};b.p=function(a){var c=
r.apply(m,k.call(arguments,1));return b.filter(a,function(a){return!b.contains(c,a)})};b.Ca=function(){for(var a=b.max(b.h(arguments,"length").concat(0)),c=Array(a),d=0;a>d;d++)c[d]=b.h(arguments,""+d);return c};b.object=function(a,c){if(null==a)return{};for(var b={},e=0,h=a.length;h>e;e++)c?b[a[e]]=c[e]:b[a[e][0]]=a[e][1];return b};b.indexOf=function(a,c,d){if(null==a)return-1;var e=0,h=a.length;if(d){if("number"!=typeof d)return e=b.C(a,c),a[e]===c?e:-1;e=0>d?Math.max(0,h+d):d}if(u&&a.indexOf===
u)return a.indexOf(c,d);for(;h>e;e++)if(a[e]===c)return e;return-1};b.lastIndexOf=function(a,b,d){if(null==a)return-1;var e=null!=d;if(M&&a.lastIndexOf===M)return e?a.lastIndexOf(b,d):a.lastIndexOf(b);for(d=e?d:a.length;d--;)if(a[d]===b)return d;return-1};b.ma=function(a,b,d){1>=arguments.length&&(b=a||0,a=0);d=arguments[2]||1;for(var e=Math.max(Math.ceil((b-a)/d),0),h=0,f=Array(e);e>h;)f[h++]=a,a+=d;return f};b.bind=function(a,c){var d,e;if(B&&a.bind===B)return B.apply(a,k.call(arguments,1));if(!b.a(a))throw new TypeError;
return d=k.call(arguments,2),e=function(){if(!(this instanceof e))return a.apply(c,d.concat(k.call(arguments)));x.prototype=a.prototype;var b=new x;x.prototype=null;var f=a.apply(b,d.concat(k.call(arguments)));return Object(f)===f?f:b}};b.ka=function(a){var b=k.call(arguments,1);return function(){return a.apply(this,b.concat(k.call(arguments)))}};b.J=function(a){var c=k.call(arguments,1);if(0===c.length)throw Error("bindAll must be passed function names");return l(c,function(c){a[c]=b.bind(a[c],a)}),
a};b.fa=function(a,c){var d={};return c||(c=b.b),function(){var e=c.apply(this,arguments);return b.has(d,e)?d[e]:d[e]=a.apply(this,arguments)}};b.o=function(a,b){var d=k.call(arguments,2);return setTimeout(function(){return a.apply(null,d)},b)};b.defer=function(a){return b.o.apply(b,[a,1].concat(k.call(arguments,1)))};b.ua=function(a,b,d){function e(){l=!1===d.A?0:new Date;k=null;g=a.apply(h,f)}var h,f,g,k=null,l=0;d||(d={});return function(){var m=new Date;l||!1!==d.A||(l=m);var n=b-(m-l);return h=
this,f=arguments,0>=n?(clearTimeout(k),k=null,l=m,g=a.apply(h,f)):k||!1===d.xa||(k=setTimeout(e,n)),g}};b.N=function(a,b,d){var e,h=null;return function(){var f=this,g=arguments,k=d&&!h;return clearTimeout(h),h=setTimeout(function(){h=null;d||(e=a.apply(f,g))},b),k&&(e=a.apply(f,g)),e}};b.ia=function(a){var b,d=!1;return function(){return d?b:(d=!0,b=a.apply(this,arguments),a=null,b)}};b.Ba=function(a,b){return function(){var d=[a];return y.apply(d,arguments),b.apply(this,d)}};b.L=function(){var a=
arguments;return function(){for(var b=arguments,d=a.length-1;0<=d;d--)b=[a[d].apply(this,b)];return b[0]}};b.H=function(a,b){return function(){return 1>--a?b.apply(this,arguments):void 0}};b.keys=Q||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var c=[],d;for(d in a)b.has(a,d)&&c.push(d);return c};b.F=function(a){var c=[],d;for(d in a)b.has(a,d)&&c.push(a[d]);return c};b.ja=function(a){var c=[],d;for(d in a)b.has(a,d)&&c.push([d,a[d]]);return c};b.v=function(a){var c={},d;for(d in a)b.has(a,
d)&&(c[a[d]]=d);return c};b.t=b.methods=function(a){var c=[],d;for(d in a)b.a(a[d])&&c.push(d);return c.sort()};b.extend=function(a){return l(k.call(arguments,1),function(b){if(b)for(var d in b)a[d]=b[d]}),a};b.la=function(a){var b={},d=r.apply(m,k.call(arguments,1));return l(d,function(d){d in a&&(b[d]=a[d])}),b};b.ha=function(a){var c={},d=r.apply(m,k.call(arguments,1)),e;for(e in a)b.contains(d,e)||(c[e]=a[e]);return c};b.n=function(a){return l(k.call(arguments,1),function(b){if(b)for(var d in b)void 0===
a[d]&&(a[d]=b[d])}),a};b.clone=function(a){return b.w(a)?b.isArray(a)?a.slice():b.extend({},a):a};b.sa=function(a,b){return b(a),a};b.isEqual=function(a,b){return w(a,b,[],[])};b.g=function(a){if(null==a)return!0;if(b.isArray(a)||b.ca(a))return 0===a.length;for(var c in a)if(b.has(a,c))return!1;return!0};b.$=function(a){return!(!a||1!==a.nodeType)};b.isArray=t||function(a){return"[object Array]"==n.call(a)};b.w=function(a){return a===Object(a)};l("Arguments Function String Number Date RegExp".split(" "),
function(a){b["is"+a]=function(b){return n.call(b)=="[object "+a+"]"}});b.j(arguments)||(b.j=function(a){return!(!a||!b.has(a,"callee"))});"function"!=typeof/./&&(b.a=function(a){return"function"==typeof a});b.isFinite=function(a){return isFinite(a)&&!isNaN(parseFloat(a))};b.isNaN=function(a){return b.ba(a)&&a!=+a};b.Z=function(a){return!0===a||!1===a||"[object Boolean]"==n.call(a)};b.aa=function(a){return null===a};b.da=function(a){return void 0===a};b.has=function(a,b){return P.call(a,b)};b.ga=
function(){return A.e=O,this};b.b=function(a){return a};b.va=function(a,b,d){for(var e=Array(Math.max(0,a)),h=0;a>h;h++)e[h]=b.call(d,h);return e};b.random=function(a,b){return null==b&&(b=a,a=0),a+Math.floor(Math.random()*(b-a+1))};var q={escape:{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"}};q.unescape=b.v(q.escape);var R={escape:new RegExp("["+b.keys(q.escape).join("")+"]","g"),unescape:new RegExp("("+b.keys(q.unescape).join("|")+")","g")};b.q(["escape","unescape"],
function(a){b[a]=function(b){return null==b?"":(""+b).replace(R[a],function(b){return q[a][b]})}});b.result=function(a,c){if(null!=a){var d=a[c];return b.a(d)?d.call(a):d}};b.B=function(a){l(b.t(a),function(c){var d=b[c]=a[c];b.prototype[c]=function(){var a=[this.c];return y.apply(a,arguments),v.call(this,d.apply(b,a))}})};var S=0;b.za=function(a){var b=++S+"";return a?a+b:b};b.D={evaluate:/<%([\s\S]+?)%>/g,u:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var C=/(.)^/,T={"'":"'","\\":"\\","\r":"r",
"\n":"n","\t":"t","\u2028":"u2028","\u2029":"u2029"},U=/\\|'|\r|\n|\t|\u2028|\u2029/g;b.ta=function(a,c,d){function e(a){return h.call(this,a,b)}var h;d=b.n({},d,b.D);var f=0,g="__p+='";a.replace(new RegExp([(d.escape||C).source,(d.u||C).source,(d.evaluate||C).source].join("|")+"|$","g"),function(b,c,d,e,h){return g+=a.slice(f,h).replace(U,function(a){return"\\"+T[a]}),c&&(g+="'+\n((__t=("+c+"))==null?'':_.escape(__t))+\n'"),d&&(g+="'+\n((__t=("+d+"))==null?'':__t)+\n'"),e&&(g+="';\n"+e+"\n__p+='"),
f=h+b.length,b});g+="';\n";d.l||(g="with(obj||{}){\n"+g+"}\n");g="var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};\n"+g+"return __p;\n";try{h=new Function(d.l||"obj","_",g)}catch(k){throw k.source=g,k;}return c?h(c,b):(e.source="function("+(d.l||"obj")+"){\n"+g+"}",e)};b.f=function(a){return b(a).f()};b.B(b);l("pop push reverse shift sort splice unshift".split(" "),function(a){var c=m[a];b.prototype[a]=function(){var b=this.c;return c.apply(b,arguments),"shift"!=
a&&"splice"!=a||0!==b.length||delete b[0],v.call(this,b)}});l(["concat","join","slice"],function(a){var c=m[a];b.prototype[a]=function(){return v.call(this,c.apply(this.c,arguments))}});b.extend(b.prototype,{f:function(){return this.m=!0,this},value:function(){return this.c}})}.call(this);
